# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhaoPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, null=True)),
                ('url_id', models.CharField(max_length=255, null=True, unique=True)),
                ('pname', models.CharField(max_length=255, null=True)),
                ('smoney', models.IntegerField(null=True)),
                ('emoney', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('syear', models.IntegerField(null=True)),
                ('eyear', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=255, null=True)),
                ('ptype', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('date_pub', models.DateField()),
                ('advantage', models.CharField(max_length=1000, null=True)),
                ('jobdesc', models.TextField(null=True)),
                ('jobaddr', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('spider_name', models.CharField(max_length=255, null=True)),
                ('crawl_time', models.DateField()),
                ('ages', models.CharField(max_length=255, null=True)),
                ('planguage', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'lagou_job',
            },
        ),
    ]
