# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhaopin',
            name='crawl_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='zhaopin',
            name='date_pub',
            field=models.DateField(null=True),
        ),
    ]
